export enum WsMessageType {
  PRICE_UPDATE = 'PRICE_UPDATE',
  PING = 'PING',
  PONG = 'PONG',
  SUBSCRIBE = 'SUBSCRIBE',
  ERROR = 'ERROR',
}

export enum ErrorCode {
  INVALID_JSON = 'INVALID_JSON',
  INVALID_MESSAGE_FORMAT = 'INVALID_MESSAGE_FORMAT',
  SUBSCRIBE_NOT_SUPPORTED = 'SUBSCRIBE_NOT_SUPPORTED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}